// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzN1yq5RJ0U397lso2oNhzFHWSPXf1egk',
    appId: '1:522393483539:web:db43958a07a3dc660e02e6',
    messagingSenderId: '522393483539',
    projectId: 'west-irbid-4f42c',
    authDomain: 'west-irbid-4f42c.firebaseapp.com',
    storageBucket: 'west-irbid-4f42c.firebasestorage.app',
    measurementId: 'G-H8H7WP0LDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1akRiXY6RZ9f7PpCp9TtytqTkLoNEyDo',
    appId: '1:522393483539:android:ad707d9ade2dd7850e02e6',
    messagingSenderId: '522393483539',
    projectId: 'west-irbid-4f42c',
    storageBucket: 'west-irbid-4f42c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwqxQIN5T1CzvrtLEyo3_w5RnwUF_PvEc',
    appId: '1:522393483539:ios:a62efc32afc3b31c0e02e6',
    messagingSenderId: '522393483539',
    projectId: 'west-irbid-4f42c',
    storageBucket: 'west-irbid-4f42c.firebasestorage.app',
    iosBundleId: 'com.example.westIrbidMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK1wnTHl-ro_vdDI0n60b1rrETk6QO_-A',
    appId: '1:522393483539:web:61c60f4c63c629230e02e6',
    messagingSenderId: '522393483539',
    projectId: 'west-irbid-4f42c',
    authDomain: 'west-irbid-4f42c.firebaseapp.com',
    storageBucket: 'west-irbid-4f42c.firebasestorage.app',
    measurementId: 'G-66EW5CTY5Q',
  );
}
